### ISSUE TITLE
Mardown syntax not working when var or block does not begin in the first char of a line

### ISSUE THREAD

**Issue by jtplaarj** [samuelcolvin/jinjahtml-vscode#98] opened 2021-10-29 07:43 UTC
Mardown syntax not working when var or block does not begin in the first char of a line.

For example:

```markdown
# whatever

{% for x in whatever %}
{{ x }}
{% endfor %}
```
works but

```markdown
# whatever

{% for x in whatever %}
- {{ x }}
{% endfor %}
```

does not

**Comment by RedCMD** [comment] 2022-08-20 04:04
Caused by the Markdown grammar
![image](https://user-images.githubusercontent.com/33529441/185728167-d48fa5f2-e1e3-4aec-9bb5-25da11e56949.png)

It may be possible to setup `injections` to fix it, but would very likely end up causing more issues

**Comment by samuelcolvin** [comment] 2022-08-20 05:33
Thanks for the explanation, closing.

**Closed by samuelcolvin** 2022-08-20 05:33 UTC
