### ISSUE TITLE
breaks css intellisense 

### ISSUE THREAD

**Issue by mberest** [samuelcolvin/jinjahtml-vscode#102] opened 2022-03-02 21:27 UTC
Could you please make you product compatible with css intellisense extensions?  (I've tried all I could find and none work when Better Jinja is installed).  Thanks!

**Comment by samuelcolvin** [comment] 2022-08-17 08:20
duplicate of #55 i fear, might get solved by #109

**Closed by samuelcolvin** 2022-08-17 08:20 UTC
