### ISSUE TITLE
Jinja HTML: Jinja syntax inside html tags is not highlighted well

### ISSUE THREAD

**Issue by whong-art** [samuelcolvin/jinjahtml-vscode#54] opened 2020-05-03 23:44 UTC
<img width="690" alt="Screen Shot 2020-05-03 at 4 42 37 PM" src="https://user-images.githubusercontent.com/40582639/80928957-2fb3aa00-8d5d-11ea-9108-06dd85744be2.png">

Would be nice to have Jinja syntax highlighted even within html tag scope

VS Code:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (2 wks ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Better Jinja: 0.12.0

Python: 3.7.7

**Comment by samuelcolvin** [comment] 2020-05-05 10:37
duplicate of #12

**Closed by samuelcolvin** 2020-05-05 10:37 UTC
