### ISSUE TITLE
VS Code is not able to find a definition of the function after enabling jinja-html

### ISSUE THREAD

**Issue by patel33hardik** [samuelcolvin/jinjahtml-vscode#78] opened 2020-12-04 02:55 UTC
Thanks for providing jinjahtml plugin.

In my current project, I used the .html page, which includes HTML, CSS, JQuery, Jinja2 template. After changing from HTML to Jinja HTML, my code not showing me any syntax errors which is good.

My issue is when I enable Jinja HTML format, the VS code can not find the function definition. I have the list of functions used in the files which are hard to find by scrolling. So, I used the definition finding tool in VS Code(using F12), but unfortunately, it's not working in the  Jinja HTML format. 

Do you have any solution that I can apply? Thanks

![function](https://user-images.githubusercontent.com/44590578/101115325-e5feab00-362e-11eb-96ef-5a0469f7c5a2.jpg)

**Comment by samuelcolvin** [comment] 2020-12-04 10:29
duplicate of #55 I think.

**Closed by samuelcolvin** 2020-12-04 10:29 UTC
