### ISSUE TITLE
Syntax highlighting issue with expressions in HTML attributes

### ISSUE THREAD

**Issue by vallentin** [samuelcolvin/jinjahtml-vscode#44] opened 2020-01-13 18:48 UTC
Using Jinja expressions and specifically strings inside HTML attributes results in incorrect syntax highlighting.

#### Example 1

```jinja
<time datetime="{{ created.format("%Y-%m-%d") }}">
```

##### Screenshot

![created](https://user-images.githubusercontent.com/17464404/72282400-dfdd9580-363c-11ea-89ae-45c8d0cc6300.png)

#### Example 2

```jinja
<link rel="stylesheet" type="text/css" href="{{ assets["/css/style.css"] }}" />
```

##### Screenshot

![assets](https://user-images.githubusercontent.com/17464404/72282410-e2d88600-363c-11ea-8e6e-2f73c6c101b5.png)

*The first example is valid Jinja in [askama](https://github.com/djc/askama), and the second is valid in [jinja](https://github.com/pallets/jinja).*

**Comment by samuelcolvin** [comment] 2020-01-13 18:51
Duplicate of #12 I guess.

**Closed by samuelcolvin** 2020-01-13 18:51 UTC
