### ISSUE TITLE
jinja inside other-language quotes seems broken

### ISSUE THREAD

**Issue by akdor1154** [samuelcolvin/jinjahtml-vscode#56] opened 2020-06-25 07:28 UTC
In Jinja I should be able to use object literals as a sort of switch statement:

```j2
{% set mode = "english" %}
greeting: "{{ {
  "english": "hi",
  "vn": "chao"
}[mode] }}, akdor1154!"
```

However this appears to confuse your highlighter when the jinja block is inside quotes of the outer language. Not entirely sure what's going on but if I do a couple of them in sequence then colours go stupid etc. I'm using jinja-yaml but I use jinja-python, jinja-markdown, i can reproduce. Cannot reproduce with jinja-html or jinja-xml though which was kind of weird.

**Comment by akdor1154** [comment] 2020-06-25 07:30
i don't fully understand how vscode highlighting works, but at a guess, this might be because the outer language grammar specifies that its strings are single-line?

**Comment by samuelcolvin** [comment] 2020-06-25 08:31
duplicate of #55

**Closed by samuelcolvin** 2020-06-25 08:31 UTC

**Comment by akdor1154** [comment] 2020-06-25 11:18
I don't think this is related as it doesn't need any language features, it's just due to how the highlight syntax grammar is constructed. It looks like (i am still reading the docs and getting up to speed) that you have both yaml's and jinja's grammar matchers on the "same level" (though jinja is applied first, maybe). However according to https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages it's maybe possible to set up a proper concept of an embedded language (here, YAML would be embedded inside Jinja, it's an open question if vs code can deal with the embedded scopes "continuing" around the blocks of jinja).

**Comment by samuelcolvin** [comment] 2020-06-25 12:26
>  it's an open question if vs code can deal with the embedded scopes "continuing" around the blocks of jinja

I think the point is that it can't, that's what's explained in #55 and the many linked issues.

Maybe I'm wrong, very happy to accept a PR if you can find a way to fix this.
